name: Build and Deploy to FTP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build static site
      run: npm run build
      
    - name: Deploy to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: "${{ secrets.FTP_HOST }}"
        username: "${{ secrets.FTP_USERNAME }}"
        password: "${{ secrets.FTP_PASSWORD }}"
        local-dir: ./dist/
        server-dir: "${{ secrets.FTP_DIRECTORY }}"
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env
          **/.DS_Store 